version: '3.9'
# start mongo services: docker-compose up -d
# stop mongo services: docker-compose down
# restart service: docker restart mongo
# stop service: docker stop mongo
# start service: docker start mongo
# remove service: docker stop mongo && docker rm mongo
services:
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - 27017:27017
    volumes:
      - ~/data:/data/db

  website-builder-fe:
    image: docker.pkg.github.com/petriadrian/website-builder-fe/website-builder-fe:dev
    build: ./
    container_name: website-builder-fe
    ports:
      - 80:80
  
  website-builder-be:
    image: docker.pkg.github.com/petriadrian/website-builder-be/website-builder-be:dev
    container_name: website-builder-be
    build: ./
    ports:
      - 8080:8080
    environment:
      - DB=mongo
    links:
      - mongo

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: unless-stopped
    ports:
      - 8081:8081

