version: '3.8'
# start mongo services: docker-compose up -d
# stop mongo services: docker-compose down
# restart service: docker restart mongo
# stop service: docker stop mongo
# start service: docker start mongo
# remove service: docker stop mongo && docker rm mongo
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - 27017:27017
    volumes:
      - ~/data/db:/data/db
      - ~/data/log/:/var/log/mongodb/

  website-builder-fe:
    image: docker.pkg.github.com/petriadrian/website-builder-fe/website-builder-fe:dev
    #    image: website-builder-fe
    build: ./
    container_name: website-builder-fe
    ports:
      - 9000:9000

  website-builder-be:
    image: docker.pkg.github.com/petriadrian/website-builder-be/website-builder-be:dev
    #    image: website-builder-be
    container_name: website-builder-be
    build: ./
    ports:
      - 8080:8080
    environment:
      - DB=mongodb
      - SPRING_PROFILES_ACTIVE=prod
    links:
      - mongodb
