# A workflow is a configurable automated process made up of one or more jobs. 
# You must create a YAML file to define your workflow configuration
# https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions
name: Auto deploy
on: 
  push:
    branches:
      - master

jobs:
  build:
    name: deploy
    runs-on: [self-hosted]
    steps:
      - uses: actions/checkout@v2
      - name: Login to DockerHub Registry
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login docker.pkg.github.com -u ${{ github.repository }} --password-stdin
      - run: make build -B
      - run: make push -B
      - run: make deploy -B
