name: Build & deploy
on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build Docker
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo ${{ secrets.GITHUB_TOKEN }} | docker login docker.pkg.github.com -u ${{ github.repository }} --password-stdin
      - run: docker-compose build website-builder-be
      - run: docker-compose push website-builder-be

  deploy:
    needs: [build]
    name: Deploy Docker
    runs-on: ubuntu-latest
    steps:
      - name: Start containers
        uses: jderusse/ga-ssh@master
        with:
          host: 167.99.196.145
          username: root
          private_key: ${{secrets.DO_PRIVATE_KEY}}
          script: |
            #  echo 45192e2f6829c5cee67369c239810161975fab16 | docker login docker.pkg.github.com -u petriadrian --password-stdin
            echo ${{ secrets.GITHUB_TOKEN }} | docker login docker.pkg.github.com -u ${{ github.repository }} --password-stdin
            docker-compose pull
            docker-compose up -d
