name: Auto deploy
on: 
  push:
    branches:
      - master

jobs:
  build:
    name: deploy
    runs-on: [self-hosted]
    steps:
      - uses: actions/checkout@v2
      - name: Login to DockerHub Registry
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login docker.pkg.github.com -u ${{ github.repository }} --password-stdin
      - run: make build -B
      - run: make push -B
      - run: make deploy -B
